jwt:
  secret: test-centwong-123-456-789-101112-131415-161718-192021_AZXCVBNM<>?

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    nacos:
      discovery:
        server-addr: localhost:8849
#        server-addr: nacos:8848
    gateway:
      discovery.locator:
        enabled: true