spring:
  flyway:
    url: jdbc:mysql://mysql:3306/parent
    locations: classpath:/db/migration
    user: root
    password: centwong
  datasource:
    url: jdbc:mysql://mysql:3306/parent
    username: root
    password: centwong
  jpa:
    show-sql: true