# =============================== SPRING CFG ===========================================

spring:
  flyway:
#    url: jdbc:mysql://mysql:3306/parent
    url: jdbc:mysql://localhost:3306/parent
    locations: classpath:/db/migration
    user: root
    password: centwong
  datasource:
#    url: jdbc:mysql://mysql:3306/parent
    url: jdbc:mysql://localhost:3306/parent
    username: root
    password: centwong
  jpa:
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849

# =============================== SWAGGER-UI CFG ===========================================
springdoc:
  swagger-ui:
    path: /swagger/index.html
  use-fqn: true

# =============================== JWT CFG ===========================================
jwt:
  secret: test-centwong-123-456-789-101112-131415-161718-192021_AZXCVBNM<>?

management:
  endpoints:
    web:
      exposure:
        include: "*"